version: '3'

services:
  php:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: database
      MYSQL_USER: nuancce
      MYSQL_PASSWORD: 1